#include "tflite_micro_model_config.h"
#pragma once


// Create #defines to enable kernel implementations
// based on the accelerators supported by the built platform


#if defined(MVPV1_COMPILED_KERNELS_ONLY)
  #undef MVPV1_KERNELS_ENABLED
  #ifndef MVPV1_COMPILED_KERNELS_ENABLED
    #define MVPV1_COMPILED_KERNELS_ENABLED
  #endif
#endif

// By default, the kernel fallback implementations are enabled
#ifndef MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#define MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT 1
#endif

#if !defined(MVPV1_KERNELS_CONV2D_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_CONV2D_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_TRANSPOSE_CONV_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_TRANSPOSE_CONV_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_DEPTHWISE_CONV2D_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_DEPTHWISE_CONV2D_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_FULLY_CONNECTED_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_FULLY_CONNECTED_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_ADD_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_ADD_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_CONCATENATION_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_CONCATENATION_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_MEAN_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_MEAN_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_MUL_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_MUL_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_PAD_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_PAD_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_RESHAPE_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_RESHAPE_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_MAX_POOL2D_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_MAX_POOL2D_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif

#if !defined(MVPV1_KERNELS_AVERAGE_POOL2D_FALLBACK_ENABLED)
 #define MVPV1_KERNELS_AVERAGE_POOL2D_FALLBACK_ENABLED MVPV1_KERNELS_FALLBACK_ENABLED_DEFAULT
#endif