#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_I2S_PRESENT
#define SL_CATALOG_I2S_I2S0_PRESENT
#define SL_CATALOG_LED0_PRESENT
#define SL_CATALOG_LED_PRESENT
#define SL_CATALOG_LED_LED0_PRESENT
#define SL_CATALOG_CPP_SUPPORT_PRESENT
#define SL_CATALOG_SL_CORE_PRESENT
#define SL_CATALOG_SL_MAIN_PRESENT
#define SL_CATALOG_SLEEPTIMER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
