// Auto-generated by AI/ML extension, do not modify

/***************************************************************************/ /**
 * @file sl_ml_model_keyword_spotting.h
 * @brief Top level functions and structures for initializing and executing a
 * machine learning model with tensorflow lite micro
 *******************************************************************************
 * # License
 * <b>Copyright 2025 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#pragma once

#include "sl_status.h"
#include "keyword_spotting_generated.h"
#include "tflite_micro_model_config.h"

using namespace npu_toolkit;

static TfliteMicroModel keyword_spotting_model;
static sl_status_t keyword_spotting_model_status;

uint8_t* keyword_spotting_model_flatbuffer = npu_toolkit_model;
const int keyword_spotting_model_flatbuffer_length = npu_toolkit_model_length;

sl_status_t slx_ml_keyword_spotting_model_init(void) {
  keyword_spotting_model_status = load_tflite_micro_model(keyword_spotting_model) ? SL_STATUS_OK : SL_STATUS_FAIL;
  return keyword_spotting_model_status;
}

sl_status_t slx_ml_keyword_spotting_model_run(void) {
  if (keyword_spotting_model_status != SL_STATUS_OK) {
    return SL_STATUS_FAIL;
  }

  keyword_spotting_model_status = keyword_spotting_model.invoke() ? SL_STATUS_OK : SL_STATUS_FAIL;
  return keyword_spotting_model_status;
}